name: Laravel

on:
  push:
    branches: [ main,dev ]
  pull_request:
    branches: [ main,dev ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: |
        cp .env.example .env
        php artisan key:generate
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Run Laravel Testing
      run: php artisan test
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
       username: "espresso"
       host: "147.182.180.196"
       password: "s9A76h8Dr=@i$r9cratr"
       script: 'cd /var/www/Espresso/ && ./server_deploy.sh'
